spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@eureka:8761/eureka

feign:
  coupon:
    url: gateway:8080